version: "3.8"
services:
 database:
  container_name: database
  image: mysql:latest
  environment:
    - MYSQL_ROOT_PASSWORD=tiger
    - MYSQL_DATABASE=demodrive
  ports: 
      - 9911:3306
 app:
    restart: always
    depends_on:
      - database
    build: ./
    ports:
      - 8888:7071
    
    
      
        
        
      
      